// Flat config: antfu's preset composed through @nuxt/eslint so it understands
// Nuxt's auto-imports (useFetch, defineEventHandler, ref, computed, …).
// `.nuxt/eslint.config.mjs` is generated by `nuxt prepare` (runs on postinstall).
import antfu from '@antfu/eslint-config'
import withNuxt from './.nuxt/eslint.config.mjs'

export default withNuxt(
  antfu({
    vue: true,
    typescript: true,
    // don't lint fenced code blocks inside README/docs prose
    markdown: false,
  }),
  {
    rules: {
      // synopsis is self-authored markdown, rendered via a sanitizing helper
      'vue/no-v-html': 'off',
      // panel payloads are loosely-typed JSON from the API
      'ts/no-explicit-any': 'off',
      // the live exporter and seed log progress to stdout
      'no-console': 'off',
      // Nitro/unenv provides `process` as a global in server code; importing
      // 'node:process' duplicates the declaration and crashes the Vercel runtime.
      'node/prefer-global/process': 'off',
    },
  },
)
